import {
  AirportConnections,
  ApartmentHunting,
  BalancedBrackets,
  BinarySearch,
  BoggleBoard,
  BranchSums,
  BreadthFirst,
  BSTConstruction,
  BSTTraversal,
  BubbleSort,
  CalendarMatching,
  CeasarCipherEncryptor,
  ContinuousMedian,
  DepthFirstSearch,
  DiskStacking,
  FindClosestValueBST,
  FindLoop,
  FindThreeLargestNumbers,
  FourNumberSum,
  GroupAnagrams,
  HeapSort,
  InsertionSort,
  InterweavingStrings,
  InvertBinaryTree,
  IterativeInorderTraversal,
  Kadanes,
  KnapsackProblem,
  KnutheMorrisPratt,
  LargestRange,
  LevenshteinDistance,
  LinkedListConstruction,
  LongestCommonSubSequence,
  LongestIncreasingSubsequence,
  LongestPalidronmicSubString,
  LongestStringChain,
  LongestSubstringWithoutDuplication,
  LRUCache,
  MaxPathSum,
  MaxProfitWithKTransactions,
  MaxSubsetSumNoAdjacent,
  MaxSumIncreasingSubsequence,
  MergeLinkedList,
  MergeSort,
  MinHeapConstruction,
  MinMaxStackConstruction,
  MinNumberOfCoinsForChange,
  MinNumberOfJumps,
  MinRewards,
  MoveElementToEnd,
  MultiStringSearch,
  NthFibonacci,
  NumberOfBinaryTreeTopologies,
  NumberOfWayToMakeChange,
  NumbersInPi,
  PalidromeCheck,
  PalindromePartitioningMinCuts,
  PatternMatcher,
  Permutations,
  Powerset,
  ProductSum,
  QuickSelect,
  QuickSort,
  RectangleMania,
  RemoveNthNodeFromEnd,
  ReverseLinkedList,
  RiverSizes,
  SameBST,
  SearchForRange,
  SearchInSortedMatrix,
  SelectionSort,
  ShiftedBinarySearch,
  SingleCycleCheck,
  SmallestDifference,
  SmallestSubstringContaining,
  SubArraySort,
  SuffixTrieConstruction,
  TopologicalSort,
  TwoNumberSum,
  UnderscorigySubString,
  ValidateBST,
  WaterArea,
  YoungestCommonAncestor,
  ZigZagTraverse,
  LargerThanPrev
} from './components/index'

export const components = 
[
{
  id: 1,
  name: "AirportConnections",
  component: <AirportConnections/>,
},
{
  id: 2,
  name: "ApartmentHunting",
  component: <ApartmentHunting/>,
  completed: false,
},
{
  id: 3,
  name: "BalancedBrackets",
  component: <BalancedBrackets/>,
  completed: false,
},
{
  id: 4,
  name: "BinarySearch",
  component: <BinarySearch/>,
  completed: false,
},
{
  id: 5,
  name: "BoggleBoard",
  component: <BoggleBoard/>,
  completed: false,
},
{
  id: 6,
  name: "BranchSums",
  component: <BranchSums/>,
  completed: false,
},
{
  id: 7,
  name: "BreadthFirst",
  component: <BreadthFirst/>,
  completed: false,
},
{
  id: 8,
  name: "BSTConstruction",
  component: <BSTConstruction/>,
  completed: false,
},
{
  id: 9,
  name: "BSTTraversal",
  component: <BSTTraversal/>,
  completed: false,
},
{
  id: 10,
  name: "BubbleSort",
  component: <BubbleSort/>,
  completed: false,
},
{
  id: 11,
  name: "CalendarMatching",
  component: <CalendarMatching/>,
  completed: false,
},
{
  id: 12,
  name: "CeasarCipherEncryptor",
  component: <CeasarCipherEncryptor/>,
  completed: false,
},
{
  id: 13,
  name: "ContinuousMedian",
  component: <ContinuousMedian/>,
  completed: false,
},
{
  id: 14,
  name: "DepthFirstSearch",
  component: <DepthFirstSearch/>,
  completed: false,
},
{
  id: 15,
  name: "DiskStacking",
  component: <DiskStacking/>,
  completed: false,
},
{
  id: 16,
  name: "FindClosestValueBST",
  component: <FindClosestValueBST/>,
  completed: false,
},
{
  id: 17,
  name: "FindLoop",
  component: <FindLoop/>,
  completed: false,
},
{
  id: 18,
  name: "FindThreeLargestNumbers",
  component: <FindThreeLargestNumbers/>,
  completed: false,
},
{
  id: 19,
  name: "FourNumberSum",
  component: <FourNumberSum/>,
  completed: false,
},
{
  id: 20,
  name: "GroupAnagrams",
  component: <GroupAnagrams/>,
  completed: false,
},
{
  id: 21,
  name: "HeapSort",
  component: <HeapSort/>,
  completed: false,
},
{
  id: 22,
  name: "InsertionSort",
  component: <InsertionSort/>,
  completed: false,
},
{
  id: 23,
  name: "InterweavingStrings",
  component: <InterweavingStrings/>,
  completed: false,
},
{
  id: 24,
  name: "InvertBinaryTree",
  component: <InvertBinaryTree/>,
  completed: false,
},
{
  id: 25,
  name: "IterativeInorderTraversal",
  component: <IterativeInorderTraversal/>,
  completed: false,
},
{
  id: 26,
  name: "Kadanes",
  component: <Kadanes/>,
  completed: false,
},
{
  id: 27,
  name: "KnapsackProblem",
  component: <KnapsackProblem/>,
  completed: false,
},
{
  id: 28,
  name: "KnutheMorrisPratt",
  component: <KnutheMorrisPratt/>,
  completed: false,
},
{
  id: 29,
  name: "LargestRange",
  component: <LargestRange/>,
  completed: false,
},
{
  id: 30,
  name: "LevenshteinDistance",
  component: <LevenshteinDistance/>,
  completed: false,
},
{
  id: 31,
  name: "LinkedListConstruction",
  component: <LinkedListConstruction/>,
  completed: false,
},
{
  id: 32,
  name: "LongestCommonSubSequence",
  component: <LongestCommonSubSequence/>,
  completed: false,
},
{
  id: 33,
  name: "LongestIncreasingSubsequence",
  component: <LongestIncreasingSubsequence/>,
  completed: false,
},
{
  id: 34,
  name: "LongestPalidronmicSubString",
  component: <LongestPalidronmicSubString/>,
  completed: false,
},
{
  id: 35,
  name: "LongestStringChain",
  component: <LongestStringChain/>,
  completed: false,
},
{
  id: 36,
  name: "LongestSubstringWithoutDuplication",
  component: <LongestSubstringWithoutDuplication/>,
  completed: false,
},
{
  id: 37,
  name: "LRUCache",
  component: <LRUCache/>,
  completed: false,
},
{
  id: 38,
  name: "MaxPathSum",
  component: <MaxPathSum/>,
  completed: false,
},
{
  id: 39,
  name: "MaxProfitWithKTransactions",
  component: <MaxProfitWithKTransactions/>,
  completed: false,
},
{
  id: 40,
  name: "MaxSubsetSumNoAdjacent",
  component: <MaxSubsetSumNoAdjacent/>,
  completed: false,
},
{
  id: 41,
  name: "MaxSumIncreasingSubsequence",
  component: <MaxSumIncreasingSubsequence/>,
  completed: false,
},
{
  id: 42,
  name: "MergeLinkedList",
  component: <MergeLinkedList/>,
  completed: false,
},
{
  id: 43,
  name: "MergeSort",
  component: <MergeSort/>,
  completed: false,
},
{
  id: 44,
  name: "MinHeapConstruction",
  component: <MinHeapConstruction/>,
  completed: false,
},
{
  id: 45,
  name: "MinMaxStackConstruction",
  component: <MinMaxStackConstruction/>,
  completed: false,
},
{
  id: 46,
  name: "MinNumberOfCoinsForChange",
  component: <MinNumberOfCoinsForChange/>,
  completed: false,
},
{
  id: 47,
  name: "MinNumberOfJumps",
  component: <MinNumberOfJumps/>,
  completed: false,
},
{
  id: 48,
  name: "MinRewards",
  component: <MinRewards/>,
  completed: false,
},
{
  id: 49,
  name: "MoveElementToEnd",
  component: <MoveElementToEnd/>,
  completed: false,
},
{
  id: 50,
  name: "MultiStringSearch",
  component: <MultiStringSearch/>,
  completed: false,
},
{
  id: 51,
  name: "NthFibonacci",
  component: <NthFibonacci/>,
  completed: false,
},
{
  id: 52,
  name: "NumberOfBinaryTreeTopologies",
  component: <NumberOfBinaryTreeTopologies/>,
  completed: false,
},
{
  id: 53,
  name: "NumberOfWayToMakeChange",
  component: <NumberOfWayToMakeChange/>,
  completed: false,
},
{
  id: 54,
  name: "NumbersInPi",
  component: <NumbersInPi/>,
  completed: false,
},
{
  id: 55,
  name: "PalidromeCheck",
  component: <PalidromeCheck/>,
  completed: false,
},
{
  id: 56,
  name: "PalindromePartitioningMinCuts",
  component: <PalindromePartitioningMinCuts/>,
  completed: false,
},
{
  id: 57,
  name: "PatternMatcher",
  component: <PatternMatcher/>,
  completed: false,
},
{
  id: 58,
  name: "Permutations",
  component: <Permutations/>,
  completed: false,
},
{
  id: 59,
  name: "Powerset",
  component: <Powerset/>,
  completed: false,
},
{
  id: 60,
  name: "ProductSum",
  component: <ProductSum/>,
  completed: false,
},
{
  id: 61,
  name: "QuickSelect",
  component: <QuickSelect/>,
  completed: false,
},
{
  id: 62,
  name: "QuickSort",
  component: <QuickSort/>,
  completed: false,
},
{
  id: 63,
  name: "RectangleMania",
  component: <RectangleMania/>,
  completed: false,
},
{
  id: 64,
  name: "RemoveNthNodeFromEnd",
  component: <RemoveNthNodeFromEnd/>,
  completed: false,
},
{
  id: 65,
  name: "ReverseLinkedList",
  component: <ReverseLinkedList/>,
  completed: false,
},
{
  id: 66,
  name: "RiverSizes",
  component: <RiverSizes/>,
  completed: false,
},
{
  id: 67,
  name: "SameBST",
  component: <SameBST/>,
  completed: false,
},
{
  id: 68,
  name: "SearchForRange",
  component: <SearchForRange/>,
  completed: false,
},
{
  id: 69,
  name: "SearchInSortedMatrix",
  component: <SearchInSortedMatrix/>,
  completed: false,
},
{
  id: 70,
  name: "SelectionSort",
  component: <SelectionSort/>,
  completed: false,
},
{
  id: 71,
  name: "ShiftedBinarySearch",
  component: <ShiftedBinarySearch/>,
  completed: false,
},
{
  id: 72,
  name: "SingleCycleCheck",
  component: <SingleCycleCheck/>,
  completed: false,
},
{
  id: 73,
  name: "SmallestDifference",
  component: <SmallestDifference/>,
  completed: false,
},
{
  id: 74,
  name: "SmallestSubstringContaining",
  component: <SmallestSubstringContaining/>,
  completed: false,
},
{
  id: 75,
  name: "SubArraySort",
  component: <SubArraySort/>,
  completed: false,
},
{
  id: 76,
  name: "SuffixTrieConstruction",
  component: <SuffixTrieConstruction/>,
  completed: false,
},
{
  id: 77,
  name: "TopologicalSort",
  component: <TopologicalSort/>,
  completed: false,
},
{
  id: 78,
  name: "TwoNumberSum",
  component: <TwoNumberSum/>,
  completed: true,
  difficulty: 'easy',
},
{
  id: 79,
  name: "UnderscorigySubString",
  component: <UnderscorigySubString/>,
  completed: false,
},
{
  id: 80,
  name: "ValidateBST",
  component: <ValidateBST/>,
  completed: false,
},
{
  id: 81,
  name: "WaterArea",
  component: <WaterArea/>,
  completed: false,
},
{
  id: 82,
  name: "YoungestCommonAncestor",
  component: <YoungestCommonAncestor/>,
  completed: false,
},
{
  id: 83,
  name: "ZigZagTraverse",
  component: <ZigZagTraverse/>,
  completed: false,
},
{
  id: 84,
  name: "LargerThanPrev",
  component: <LargerThanPrev/>,
  completed: true,
  difficulty: 'easy',
},

]
